language: perl6

perl6:
  - nom
  - latest

os:
  - osx
  - linux

before_install:
  - PKG="sudo apt-get";
  - if [ "$TRAVIS_OS_NAME" = "osx" ];  then PKG=brew; fi;
  - $PKG install taglib

install:
  - rakudobrew build zef
  - zef install --depsonly .

script: prove -v -e "perl6 -Ilib" t/
